const css = {
  searchBarInput: {
    fontFamily: "Corben_400Regular",
    fontSize: 20,
    paddingTop: "5%",
    color: "#242424",
  },
  searchBar: {
    width: "95%",
    height: 60,
    backgroundColor: "#ffffffff",
    borderRadius: 15,
    borderWidth: 3,
    borderColor: "#242424",
    zIndex: 999,
    padding: 0,
    margin: "auto",
    marginBottom: 20,
  },
  body: {
    flex: 1,
    fontFamily: "Corben_400Regular",
    fontSize: 10,
    backgroundColor: "#fff",
  },
  pillsView: {
    maxHeight: "85%",
    maxWidth: "95%",
    padding: 1,
    fontSize: 10,
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-start",
    flexWrap: "wrap",
    columnGap: 5,
    rowGap: 10,
    margin: "auto",
  },
  pill: {
    borderRadius: 50,
    borderWidth: 0,
    backgroundColor: "#b147ff99",
    borderWidth: 2,
    borderColor: "#b147ff22",
    color: "black",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  pillText: {
    fontFamily: "Corben_400Regular",
    fontSize: 15,
    color: "ghostwhite",
    textAlign: "center",
    textAlignVertical: "center", // Android only
    includeFontPadding: false, // Android only
  },

  card: {
    width: "95%",
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    padding: 20,
    borderWidth: 2,
    borderColor: "#b147ff22",
    backgroundColor: "#2196f303",
    shadowColor: "#708090",
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    marginTop: 10,
  },
  cardTitle: {
    fontFamily: "Corben_400Regular",
    fontSize: 16,
    textAlign: "center",
    color: "#b147ff99",
    marginBottom: 10,
    lineHeight: 25,
  },
  cardSummary: {
    fontFamily: "Corben_400Regular",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
    color: "#4d769f",
  },
  listView: {
    padding: 10,
    fontSize: 10,
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    columnGap: 5,
    rowGap: 10,
  },
  swipeableView: {
    flex: 1,
    marginTop: "10%",
  },
  contentView: {
    padding: 12,
    paddingBottom: 60,
    marginTop: "12%",
    maxHeight: "90%",
  },
  contentTitle: {
    fontFamily: "Corben_400Regular",
    fontSize: 25,
    lineHeight: 35,
    textAlign: "left",
    color: "#b147ff99",
  },

  section: {
    alignSelf: "left",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  sectionTitle: {
    flex: 8,
    fontFamily: "Corben_400Regular",
    fontSize: 20,
    textAlign: "left",
    color: "#4d769f",
    lineHeight: 30,
  },
  contentSummary: {
    marginTop: 15,
    fontFamily: "Corben_400Regular",
    fontSize: 16,
    lineHeight: 20,
    textAlign: "left",
    color: "#4d769f",
  },
  sectionIcon: {
    color: "#b147ff99",
    flex: 2,
    margin: "auto",
    textAlign: "right",
  },
  visible: {
    display: "flex",
  },
  invisible: {
    display: "none",
  },
  sectionContent: {
    marginTop: 10,
    fontFamily: "Corben_400Regular",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "left",
    color: "#334f6a",
  },
  sectionSubtitle: {
    marginTop: 10,

    fontFamily: "Corben_400Regular",
    fontSize: 18,
    textAlign: "left",
    color: "#334f6a",
    lineHeight: 30,
  },
  spinnerLoading: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  spinnerLoaded: {
    display: "none",
  },
};

export default css;
